### ISSUE TITLE
Two keys 'title' and 'locale' will be created automatically in JSON file

### ISSUE THREAD

**Issue by lukedesu** [kolonist/node-i18n-x#2]
hi @kolonist ,
Looks these two keys 'title' and 'locale' will be created automatically, is that designed by intention?
Thanks!

**Comment by kolonist** [comment]
No its not. And I can't get how could it be, cause there is even no word `title` in library source. Can you provide some example of your code?

// yeah, I know that a lot of time passed since your question, but if it still actual I'd like to manage it

**Comment by lukedesu** [comment]
resolved for now.
